# Generated by Django 3.1.7 on 2021-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0014_auto_20210307_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_up',
            name='v_image',
            field=models.ImageField(default='', upload_to='inno_user/images/'),
        ),
    ]
