# Generated by Django 3.1.7 on 2021-03-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0017_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='p_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='p_name',
        ),
    ]
