# Generated by Django 3.1.7 on 2021-03-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0021_auto_20210318_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_image',
            field=models.ImageField(upload_to='inno_user/profile/'),
        ),
    ]
