# Generated by Django 3.1.7 on 2021-03-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0025_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfo',
            fields=[
                ('port_id', models.AutoField(primary_key=True, serialize=False)),
                ('port_user', models.CharField(default='', max_length=20)),
                ('port_img', models.ImageField(upload_to='inno_user/portfolio/')),
                ('port_url', models.URLField(default='')),
            ],
        ),
    ]
