# Generated by Django 3.1.7 on 2021-04-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0027_auto_20210331_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_up',
            name='v_gif',
            field=models.ImageField(default='', upload_to='inno_user/Gif/'),
        ),
    ]
