# Generated by Django 3.1.7 on 2021-04-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0029_auto_20210408_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_email',
            field=models.CharField(default='', max_length=120),
        ),
    ]
