# Generated by Django 3.1.7 on 2021-04-17 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inno_user', '0029_auto_20210408_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_email',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.CreateModel(
            name='follower',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_user', models.CharField(default='', max_length=20)),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
