# Generated by Django 3.1.7 on 2021-05-23 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0030_auto_20210417_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_up',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 23)),
        ),
    ]
