# Generated by Django 3.1.7 on 2021-04-13 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inno_user', '0030_profile_p_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='follower',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('fo_id', models.IntegerField(default=0)),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
