# Generated by Django 3.1.7 on 2021-04-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0031_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='fo_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
