# Generated by Django 3.1.7 on 2021-04-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0032_auto_20210413_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='fo_id',
            new_name='f_user',
        ),
    ]
