# Generated by Django 3.1.7 on 2021-05-14 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0033_auto_20210413_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_up',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 14)),
        ),
    ]
