# Generated by Django 3.1.7 on 2021-03-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0015_video_up_v_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_up',
            name='v_image',
            field=models.ImageField(upload_to='inno_user/images/'),
        ),
    ]
