# Generated by Django 3.1.7 on 2021-03-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0016_auto_20210312_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(default='', max_length=20)),
                ('p_image', models.ImageField(upload_to='inno_user/profile/')),
                ('p_about', models.CharField(default='', max_length=120)),
                ('p_contact', models.IntegerField(default=0)),
                ('p_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
