# Generated by Django 3.1.7 on 2021-03-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0018_auto_20210316_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
