# Generated by Django 3.1.7 on 2021-03-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0020_auto_20210318_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_image',
            field=models.ImageField(default='inno_user/user.png', upload_to='inno_user/profile/'),
        ),
    ]
