# Generated by Django 3.1.7 on 2021-03-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0022_auto_20210319_1347'),
        ('inno_user', '0017_auto_20210312_2025'),
    ]

    operations = [
    ]
