# Generated by Django 3.1.7 on 2021-03-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0023_merge_20210320_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='p_html',
        ),
        migrations.AlterField(
            model_name='video_up',
            name='v_image',
            field=models.ImageField(upload_to='inno_user/images/'),
        ),
    ]
