# Generated by Django 3.1.7 on 2021-03-31 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inno_user', '0026_portfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cmt_vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inno_user.video_up'),
        ),
        migrations.AlterField(
            model_name='like',
            name='l_postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inno_user.video_up'),
        ),
        migrations.AlterField(
            model_name='like',
            name='l_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video_up',
            name='v_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
